a=input("Enter the first no.: ")
b=input("Enter the second no.: ")
a=int(a)
b=int(b)
avg=(a+b)/2
print ("1)  Average is: ",avg)
name = "Aakash"
print("2) ",name[2:4])
print("3) ",name[2:5:4])
print("4) ",len(name))
print("5) ", name.count('a'))
print("6) " , name.find('k'))
print("7) ",name.replace('a','x'))
name=input("Enter your name: ")
print("Good Afternoon ",name)
arr=[1,5,2,58,4,5]
print("8) ",arr,arr[4])
arr.sort()
print("9) ",arr)
arr.reverse()
print("10) ",arr)
arr.append(28)
print("11) ",arr)
arr.insert(1,39)
print("12) ",arr)
arr.pop(1)
print("13) ",arr)
arr.remove(58)
print("14) ",arr)
print("15) ",sum(arr))
print("16) ",arr.count(5))

